export const ADD_ITEM = 'ADD_ITEM';
export const STAR_ITEM = 'STAR_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_ITEM_ALL = 'DELETE_ITEM_ALL';
export const CHECKBOX_ITEM_ADD = 'CHECKBOX_ITEM_ADD';
export const CHECKBOX_ITEM_DELETED = 'CHECKBOX_ITEM_DELETED';