export const ADD_FRIEND = 'ADD_FRIEND';
export const STAR_FRIEND = 'STAR_FRIEND';
export const DELETE_FRIEND = 'DELETE_FRIEND';
export const DELETE_FRIEND_ALL = 'DELETE_FRIEND_ALL';
export const CHECKBOX_FRIEND_ADD = 'CHECKBOX_FRIEND_ADD';
export const CHECKBOX_FRIEND_DELETED = 'CHECKBOX_FRIEND_DELETED';