export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
export const LOGOUT = 'USERS_LOGOUT';
export const CHANGE_LOGIN = 'USERS_CHANGE_LOGIN';
export const CHANGE_PASSWORD = 'USERS_CHANGE_PASSWORD';